repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-case-conflict

  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        language: system
        types_or: [python, pyi]
        args: [--fix]
        pass_filenames: true

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format --check
        language: system
        types_or: [python, pyi]
        pass_filenames: true

      - id: ruff-security
        name: ruff security check
        entry: uv run ruff check
        language: system
        types_or: [python, pyi]
        args: [--select=S]
        pass_filenames: true
