telegram:
  bot_token: "token"
  admin_ids: [1,2,3,4]
  bot_username: "your_bot_username"

postgres:
  host: "localhost"
  port: 5432
  user: "dev_user"
  password: "dev_password"
  db: "template_app"
  # pool_size: 30
  # pool_timeout: 30
  # pool_recycle: 3600
  # max_overflow: 20
  # pool_pre_ping: true
  # echo_pool: false

auth:
  secret_key: "3d1b2a2127de6f65804364813b3107b2"
  algorithm: "HS256"
  access_token_expire_minutes: 30

log:
  level: "INFO"
