telegram:
  bot_token: "token"
  admin_ids: [1,2,3,4]
  bot_username: "your_bot_username"

postgres:
  host: "localhost"
  port: 5432
  user: "tma_user"
  password: "tma_password"
  db: "tma_db"
  # pool_size: 30
  # pool_timeout: 30
  # pool_recycle: 3600
  # max_overflow: 20
  # pool_pre_ping: true
  # echo_pool: false

auth:
  secret_key: "secret"
  algorithm: "HS256"
  access_token_expire_minutes: 30

log:
  level: "INFO"

# sentry:
#   dsn: "https://examplePublicKey@o0.ingest.sentry.io/0"
#   environment: "development"
#   traces_sample_rate: 1.0
#   profiles_sample_rate: 1.0
