FROM python:3.13-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen

COPY . .

ENV PYTHONPATH=/app/src

CMD ["uv", "run", "python", "-m", "src.presentation.bot.main"]
