FROM python:3.13-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./
RUN uv sync --frozen

COPY . .

ENV PYTHONPATH=/app/src

COPY docker/entrypoint-bot.sh /entrypoint-bot.sh
RUN chmod +x /entrypoint-bot.sh

ENTRYPOINT ["/entrypoint-bot.sh"]
