"""user

Revision ID: c6ae99a6b811
Revises:
Create Date: 2025-06-24 01:45:18.536689

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from src.infrastructure.db.models.types.user import (
    BioType,
    FirstNameType,
    LastNameType,
    UserIdType,
    UsernameType,
)

# revision identifiers, used by Alembic.
revision: str = "c6ae99a6b811"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", UserIdType(), nullable=False),
        sa.Column("first_name", FirstNameType(length=64), nullable=False),
        sa.Column("last_name", LastNameType(length=64), nullable=True),
        sa.Column("username", UsernameType(length=32), nullable=True),
        sa.Column("bio", BioType(length=160), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
