"""user

Revision ID: c6ae99a6b811
Revises:
Create Date: 2025-06-24 01:45:18.536689

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from src.infrastructure.db.models.types.user import (
    UserIdType,
    FirstNameType,
    LastNameType,
    UsernameType,
    BioType,
)


# revision identifiers, used by Alembic.
revision: str = "c6ae99a6b811"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", UserIdType(), nullable=False),
        sa.Column("first_name", FirstNameType(length=64), nullable=False),
        sa.Column("last_name", LastNameType(length=64), nullable=True),
        sa.Column("username", UsernameType(length=32), nullable=True),
        sa.Column("bio", BioType(length=160), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
