#!/usr/bin/env python3
"""Generate Python types file for fluentogram translations.

This script parses .ftl files and generates a types.py file
that provides IDE autocomplete for translation keys with runtime
compatibility via TYPE_CHECKING guard.
"""

from pathlib import Path
import re


def extract_ftl_keys(ftl_content: str) -> list[tuple[str, list[str]]]:
    """Extract translation keys and their parameters from FTL content.

    Returns list of (key_name, [param_names]).
    """
    keys = []
    lines = ftl_content.split("\n")

    i = 0
    while i < len(lines):
        line = lines[i]

        # Skip comments and empty lines
        if not line.strip() or line.strip().startswith("#"):
            i += 1
            continue

        # Match key = value pattern
        match = re.match(r"^([a-z][a-z0-9_-]*)\s*=\s*(.*)", line)
        if match:
            key = match.group(1)
            value_lines = [match.group(2)]

            # Collect multiline values
            i += 1
            while i < len(lines):
                next_line = lines[i]
                if next_line.startswith(("    ", "\t")) or (
                    not next_line.strip()
                    and i + 1 < len(lines)
                    and lines[i + 1].startswith(("    ", "\t"))
                ):
                    value_lines.append(next_line)
                    i += 1
                else:
                    break

            value = "\n".join(value_lines)

            # Extract parameters like { $param_name }
            params = re.findall(r"\{\s*\$([a-z_][a-z0-9_]*)\s*\}", value, re.IGNORECASE)
            # Remove duplicates while preserving order
            seen = set()
            unique_params = []
            for p in params:
                if p not in seen:
                    seen.add(p)
                    unique_params.append(p)

            keys.append((key, unique_params))
        else:
            i += 1

    return keys


def generate_types_content(all_keys: dict[str, list[str]]) -> str:
    """Generate types.py content with TYPE_CHECKING guard for FluentTranslator."""
    lines = [
        '"""Auto-generated types file for fluentogram translations.',
        "",
        "Generated by scripts/generate_i18n_stubs.py",
        "Do not edit manually - regenerate with: uv run python scripts/generate_i18n_stubs.py",
        '"""',
        "",
        "from typing import TYPE_CHECKING",
        "",
        "if TYPE_CHECKING:",
        "    from fluentogram import TranslatorRunner as _TranslatorRunner",
        "",
        "    type _I18nArg = str | int | float",
        "",
        "    class TranslatorRunner(_TranslatorRunner):",
        '        """Type stubs for FluentTranslator with all available translation keys."""',
        "",
    ]
    for key, params in sorted(all_keys.items()):
        # Convert kebab-case to snake_case for method name
        method_name = key.replace("-", "_")
        if params:
            param_str = ", ".join(f"{p}: _I18nArg" for p in params)
            lines.append(f"        def {method_name}(self, *, {param_str}) -> str: ...")
        else:
            lines.append(f"        def {method_name}(self) -> str: ...")

    lines.extend(
        [
            "",
            "else:",
            "    from fluentogram import TranslatorRunner  # noqa: F401",
            "",
        ]
    )

    return "\n".join(lines)


def main() -> None:
    """Generate types file from locale files."""
    project_root = Path(__file__).parent.parent
    locales_dir = project_root / "locales"
    output_file = project_root / "src" / "infrastructure" / "i18n" / "types.py"

    # Use English as the reference locale
    en_dir = locales_dir / "en"

    if not en_dir.exists():
        print(f"Error: English locale directory not found: {en_dir}")
        return

    all_keys: dict[str, list[str]] = {}

    # Parse all .ftl files in the English locale
    for ftl_file in en_dir.glob("*.ftl"):
        content = ftl_file.read_text(encoding="utf-8")
        keys = extract_ftl_keys(content)
        for key, params in keys:
            all_keys[key] = params
        print(f"Parsed {ftl_file.name}: {len(keys)} keys")

    if not all_keys:
        print("Error: No translation keys found")
        return

    # Generate types content
    types_content = generate_types_content(all_keys)

    # Write types file
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(types_content)
    print(f"\nGenerated {output_file} with {len(all_keys)} translation methods")


if __name__ == "__main__":
    main()
