"""Auto-generated type stubs for fluentogram translations.

Generated by scripts/generate_i18n_stubs.py
Do not edit manually - regenerate with: python scripts/generate_i18n_stubs.py
"""

class TranslatorRunner:
    """Type stubs for FluentTranslator with all available translation keys."""

    def bot_started(self) -> str: ...
    def example_executed(self) -> str: ...
    def welcome(self, *, name: str | int) -> str: ...
